UI improvement
digitalbazaar/bedrock-angular-identity-composer pull request #5
Opened 2017-04-17 16:13 UTC by gannan08

2017-04-17 16:58 UTC, mattcollier requested changes

2017-04-17 16:58 UTC, mattcollier commented on identity-composer-component.html
> +<!--     <h4 ng-mouseenter="$hover=true" ng-mouseleave="$hover=false">
Remove commented code if not needed.

2017-04-17 16:58 UTC, mattcollier commented on identity-composer-component.html
> +            class="fa fa-refresh fa-spin"></i>
Looks like your editor needs to be configured to remove trailing spaces.

2017-04-17 16:58 UTC, mattcollier commented on identity-composer-component.js
> +
Remove extra line.

2017-04-17 16:58 UTC, mattcollier commented on identity-composer-component.html
> +<style>
I guess this would be moved into a `less` file for this module once everyone signs off on the design.

2017-04-17 17:44 UTC, dlongley commented on identity-composer-component.html
> +<style>
All of these special classes should be prefixed as well with `br-` -- CSS classes are global.

2017-04-17 17:47 UTC, dlongley commented on identity-composer-component.html
> +                      height: calc({{$ctrl.credentialWidth.select}} * 0.0975)">
Fix indentation. Also, CSS `calc` wouldn't have to be relied upon if these calculations were performed in the controller and stored in some object for the info overlay. The factor `0.0975` could also be in the controller as a constant. Also, why is that multiplier sometimes `0.0975` and `0.10` at other points? Can something be done to make that seem less magical and easier to understand why it is what it is?

2017-04-17 17:49 UTC, davidlehn commented on identity-composer-component.html
> +        style="font-size: calc({{$ctrl.credentialWidth.select}} * 0.07)">
Could also use angular to do the math vs using `calc()`.
Should `ng-style` be used here?

2017-04-17 17:51 UTC, dlongley commented on identity-composer-component.js
> +  self.detail = function(credential, showCredential, $event) {
Naming convention for functions called in response to an event/action is: `onFoo`. So this should be something like: `onInfoClicked` or `onShowDetails` or similar.

2017-05-03 15:27 UTC, dlongley commented
ping @gannan08: changes requested here

2017-05-23 17:09 UTC, dlongley requested changes

2017-05-23 17:09 UTC, dlongley commented on main.less
> +  padding: 3.5% 5px;
This seems problematic, as in, lots of padding on large screens. Why not fixed padding and allow parent layouts that are using this class to deal with padding complexity?

2017-05-23 17:09 UTC, dlongley commented on main.less
> +}
Combine media queries into `br-text-element` (less syntax):

```css
.br-text-element {
  ...

  @media (max-width: 1440px) {
  }
  ...
}

2017-05-23 17:09 UTC, dlongley commented on main.less
> +}
Combine (group) media queries like suggested above.

2017-05-23 17:09 UTC, dlongley commented on main.less
> +@media (max-width: 767px) {
Move up to be in the rest of the `br-identity-container` definition.

2017-05-23 17:09 UTC, dlongley commented on identity-composer-component.js
> +  };
This seems kinda hacky to me ... but we can move forward with it and address later. Please mark with a "TODO: could be improved, seems hacky" so we can note it for later :)

2017-05-30 18:23 UTC, dlongley approved these changes

2017-05-30 18:30 UTC, mattcollier approved these changes

2017-05-30 18:52 UTC, merged